#ifndef MIKPLUGIN_GLOBAL_H
#define MIKPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MIKPLUGIN_LIBRARY)
#  define MIKPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MIKPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MIKPLUGIN_GLOBAL_H
